### ISSUE TITLE
Add logical operators

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#10]
And - &
Or - |
Not - !

**Comment by Atul9** [comment]
@emilsoman I would like take this up.

**Comment by emilsoman** [comment]
@Atul9 sure! Please ping me on discord if you need any help.

**Comment by Atul9** [comment]
@emilsoman as discussed I am working on https://github.com/fika-lang/fika/issues/3 hence this ^ issue can be taken up by someone else.

**Comment by emilsoman** [comment]
@Atul9 informed me he is not working on this issue anymore so this issue is up for grabs!

**Comment by v0idpwn** [comment]
I can take this one

**Comment by emilsoman** [comment]
It's yours @v0idpwn !
