### ISSUE TITLE
Add tuples

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#12]
Tuples are of the form `{"foo", 123}` which is of the type: `{String, Int}`. They are like lists, but what they will contain is already fixed at compile time and cannot contain arbitrary values.

**Comment by sreecodeslayer** [comment]
May I? 😌

**Comment by emilsoman** [comment]
Yes please!

**Comment by sreecodeslayer** [comment]
@emilsoman 
I get a feeling that the syntax for a tuple: `{1, 2}` would conflict with our existing record syntax which also starts with `{a: "1"}`.
It would seem ambiguous when parsing empty tuples and records as there is no way of distinguishing both of them, `{}` and `{}`, unlike Elixir which uses `%{}` for Maps, and `{}` for Tuples
wdyt?🤔

**Comment by polvalente** [comment]
@sreecodeslayer maybe Fika could adopt Python-style tuples with `()` instead?

**Comment by sreecodeslayer** [comment]
> @sreecodeslayer maybe Fika could adopt Python-style tuples with `()` instead?

I was looking more at the tests for records and we don't allow empty records. Nor should we allow empty tuples. Empty should be of type "Nothing" and explicit. I think this would solve the ambiguity. @emilsoman thinks so too. 😃
