### ISSUE TITLE
Add mix format --check-formatted as CI check

### ISSUE THREAD

**Issue by polvalente** [fika-lang/fika#17]
As per [my comment](https://github.com/fika-lang/fika/pull/13#discussion_r498636720) on #13, I think that formatter and credo would be nice additions to the workflow.
Since the formatter is standardized, it would be nice and simple for everyone to use.
And credo adds more code uniformity checks that might also be nice

**Comment by emilsoman** [comment]
+1 for mix format --check-formatted in CI. As for credo, we'll wait until we learn from the experience that other lang developers have of linters.
