### ISSUE TITLE
Add documentation for new contributors

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#2]
1. Add a "Contributing" section to the README.
This section should explain how to install all dependencies and get started with the dev environment for the Fika compiler. See the README of https://github.com/elixir-lang/elixir for ideas.

2. Create a `docs/architecture.md` file explaining how Fika works (DM emil on discord for help) and link it in the new README section.

**Comment by hritik5102** [comment]
Hello @emilsoman, I would like to work on this issue :)

**Comment by emilsoman** [comment]
@hritik5102 the issue is yours!

**Comment by CilgaIscan** [comment]
Can I work on this project, too? @emilsoman

**Comment by emilsoman** [comment]
@CilgaIscan this issue is assigned to someone for now. Please watch out for new issues as they are created, I'm sure there'll be something you'd like to pick up. Thank you for your offer to help!

**Comment by hritik5102** [comment]
> @hritik5102 the issue is yours!

Thank you , i'll make the neccasary changes in few second :)

**Comment by emilsoman** [comment]
@hritik5102 no hurry. I'm only preparing Fika for Hacktoberfest. Hacktoberfest only starts on Oct 1!

**Comment by hritik5102** [comment]
@emilsoman can you share the video in discord, where you explained the architecture of your system so that I can work on this issue.

Thank you :)

**Comment by emilsoman** [comment]
@hritik5102 i've already added a docs article here: https://github.com/fika-lang/fika/blob/master/docs/hacking_syntax.md. You can just link to that for now instead of creating an "architecture" doc.

**Comment by hritik5102** [comment]
so what should I do now?
should I create a fresh PR for documentation?

Please can you guide me, thank you

**Comment by emilsoman** [comment]
@hritik5102 yes please create a new PR for this, but kindly stick to the scope mentioned in the issue description. But instead of creating a `docs/architecture.md` file, you can link to the file mentioned in my previous comment. That file talks about how someone new to Fika can learn enough about how Fika works to start contributing.

**Comment by hritik5102** [comment]
Ok, got it 👍

**Comment by emilsoman** [comment]
Assigning this issue to myself.
