### ISSUE TITLE
Optimize parser compilation time

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#23]
Currently the parser combinator takes a while to compile because nimble_parsec will take quite a bit of time to create functions from all our rules. Got some pointers from Jose Valim to optimize this. One way is to split large combinators into smaller ones and put them in multiple modules. Because modules are compiled in parallel, this will have a significant effect in compilation times. Also explore the possibility of pre-compiling rarely changed parsers (white spaces, identifiers etc) and checking in the compiled functions to git.

**Comment by polvalente** [comment]
> Also explore the possibility of pre-compiling rarely changed parsers (white spaces, identifiers etc) and checking in the compiled functions to git.

@emilsoman If we're to split into different modules, segregating frequently used parsers to their respective modules should improve overall speed, because modules aren't recompiled if they aren't changed.

In this regard, a following task would be to add a build cache to the CI workflow. I didn't tackle this in #26 because I'd rather make small changes to the CI workflow each time, but this shouldn't be too difficult!

**Comment by polvalente** [comment]
Since we're using Elixir `1.10.4`, we could also look into refactoring through `defdelegate`, because [since `1.10.4` it doesn't add a compile-time dependency to modules](https://github.com/elixir-lang/elixir/releases/tag/v1.10.4).

**Comment by emilsoman** [comment]
Closed by b456e41e045a .

mix compile
===========

#### fika(before)» time mix compile
Compiling 12 files (.ex)
Compiling lib/fika/parser.ex (it's taking more than 15s)
Generated fika app
       61.69 real        59.01 user         4.77 sys

#### fika(after)» time mix compile
Compiling 18 files (.ex)
Generated fika app
        3.94 real         8.28 user         1.18 sys


mix test
========

#### fika(before)» time mix test
Compiling 12 files (.ex)
Compiling lib/fika/parser.ex (it's taking more than 15s)
Generated fika app
..................................................................................................

Finished in 1.7 seconds
98 tests, 0 failures

Randomized with seed 447499
       67.40 real        64.37 user         5.64 sys

#### fika(after)» time mix test
Compiling 19 files (.ex)
Generated fika app
..................................................................................................

Finished in 1.6 seconds
98 tests, 0 failures

Randomized with seed 573172
        5.79 real        12.49 user         1.33 sys

**Comment by emilsoman** [comment]
Leaving some more numbers regarding runtime performance:

Operating System: macOS
CPU Information: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
Number of Available Cores: 4
Available memory: 8 GB
Elixir 1.10.4
Erlang 23.1.1

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
memory time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 14 s

Name             ips        average  deviation         median         99th %
before        1.71 K      584.60 μs    ±16.40%         559 μs     1024.92 μs
after         1.56 K      640.80 μs    ±20.60%         604 μs     1157.38 μs

Comparison:
before        1.71 K
after         1.56 K - 1.10x slower +56.19 μs

![image](https://user-images.githubusercontent.com/1707078/95240949-bbf55c00-082a-11eb-9629-f9d71d25fbee.png)

![image](https://user-images.githubusercontent.com/1707078/95240651-599c5b80-082a-11eb-9b03-fe2f21379705.png)

So this does have a minor impact during runtime.
