### ISSUE TITLE
Add support for union types

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#24]
A union type is a set consisting of multiple non-overlapping types. With union types, we can have function signatures of the type:

```elixir
fn foo : {:ok, Int} | {:error, String} do
  if true do
    {:ok, 123}
  else
    {:error, "Something went wrong"}
  end
end
```

We'll need to understand the concept of subtypes before we start working on this. [This wiki](https://en.wikipedia.org/wiki/Subtyping) is a good introduction.

In this example:
![image](https://user-images.githubusercontent.com/1707078/95010225-33699680-0645-11eb-9064-032975e96198.png)
duck is a subtype of bird (which is its supertype), which means it can be substituted wherever a bird is expected. Similarly, a union type is a supertype of each member of the set.

Changes required:

1. Allow if-else branches to return different types. The inferred type of the if-else expression will be a union of the two types. This can be represented using a new "Union" struct that can be defined [here](https://github.com/fika-lang/fika/blob/master/lib/fika/types.ex) like the FunctionRef struct. The to_string function of the struct will join the types separated by " | ".
2. When [inferring the return type of a function](https://github.com/fika-lang/fika/blob/master/lib/fika/type_checker.ex#L52), we'll now expand union types and add all possible function types in [add_function_type](https://github.com/fika-lang/fika/blob/master/lib/fika/type_checker.ex#L402). Example:

```elixir
# A function that takes x which can be either :foo or :bar and returns either :ok or :error
fn foo(x: :foo | :bar) : :ok | :error do
  # ...
end
```

The type checker will add the following function types to its "function_types" map in env:
1. module.foo(:foo) => :ok 
2. module.foo(:foo) => :error
3. module.foo(:bar) => :ok
4. module.foo(:bar) => :error 

We can optimize the storing and checking of function types later, but this should do for now.

Please let me know if I've missed something here!

**Comment by polvalente** [comment]
@emilsoman can I have this one? I'll tackle this later today or in the latest, tomorrow

**Comment by emilsoman** [comment]
Sure go ahead @polvalente! Please take your time. This is going to be a big feature for Fika!
