### ISSUE TITLE
Add support for maps

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#25]
Maps will have the following syntax:

```
{"foo" => 123} # Type: Map(String, Int)
```

Don't worry about empty maps for now. We'll handle that separately. Please refer the Fika language hacking guide inside `/docs` to understand the steps involved in adding new syntax to Fika.

**Comment by polvalente** [comment]
@emilsoman in Elixir, `%{a: 1}` and `%{:a => 1}` are exactly equal. Will `{a: 1}` and `{:a => 1}` be different in Fika?

**Comment by sreecodeslayer** [comment]
How do we differentiate this from records. I mean, not by syntax but by the actual underlying use case.
In the end, we translate Record to erlang map, so am guessing Fika Maps would also be Erlang maps.

**Comment by polvalente** [comment]
@sreecodeslayer that's my concern as well. In Elixir, atom-maps are just syntatical sugar for the `%{term => term}` syntax.

```elixir
iex
Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.10.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> %{:a => 1} == %{a: 1}
true
iex(2)> %{:a => 1} === %{a: 1}
true
iex(3)> i %{:a => 1}
Term
  %{a: 1}
Data type
  Map
Reference modules
  Map
Implemented protocols
  Collectable, Enumerable, IEx.Info, Inspect
iex(4)> i %{a: 1}
Term
  %{a: 1}
Data type
  Map
Reference modules
  Map
Implemented protocols
  Collectable, Enumerable, IEx.Info, Inspect
```

**Comment by emilsoman** [comment]
In Fika: `{a: 1}` is a record and not a map at all. The only similarity records have with maps is that they both contain key-values, but records are really just static structures that are not meant to grow dynamically. That's why their type is actually just their record structures themselves. For example. A record {foo: "123"} has a type `{foo: String}`. Changing this during runtime would mean the type itself changes. But maps on the other hand grow dynamically without changing their types.

Maps are for cases when the keys are only known at runtime (think of something like HTTP headers). If we already know they keys beforehand, that's a use case for records (example: a User record that's read from the DB). Records give us type safety when accessing them and are better for passing around entities with fixed structures. Hope that makes sense.

**Comment by polvalente** [comment]
That seems like a nice separation! Maybe we could define the delimiter differently as well? It seems for me that using `{}` for tuples, maps and records leaves too much cognitive overload upon the programmer, who would have to read between the curly brackets to determine which data type is being used

**Comment by polvalente** [comment]
I suggest changing records to something like `%{}`, `@{}`, `${}`, because then if we want to introduce structs, we can treat them as named records, using Elixir-like syntax: `%Name{}`, `@Name{}` or `$Name{}` in the above cases

**Comment by emilsoman** [comment]
Point noted @polvalente . If this was confusing to contributors, this is a potential cause of confusion for users as well. But at the same time, as language hackers we may be thinking of this differently until we actually start to write code in Fika. The notation we use has been successfully used before, for example, in Crystal lang (https://crystal-lang.org/reference/ - check out Hash(maps for us), Tuple and NamedTuple(we call them records)). After Fika is ready for users, we'll make sure we get feedback and iterate on not just maps, but ALL syntax.

**Comment by sreecodeslayer** [comment]
@emilsoman if not picked by anyone, i'll take this for the weekend 😁

**Comment by emilsoman** [comment]
@sreecodeslayer feel free!
