### ISSUE TITLE
Add Github action to auto-release the latest binary

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#3]
To make it easy to get started with Fika, we need to automate the binary release
process. Check out https://github.com/spawnfest/bakeware and use github actions
to automate releases.

**Comment by eagleusb** [comment]
Hi :wave: 

I'm willing to help you create the GitHub Actions compiling your Elixir runtime and release it :)
It seems fun, let me know if you have 5 minutes to discuss it.

Leslie :cat:

**Comment by emilsoman** [comment]
@eagleusb thank you! our discussions happen in discord, hope that works for you

**Comment by Hsins** [comment]
Hi @emilsoman, I have created a PR for this issue. Note that I create the `.yml` and which trigger the GitHub Actions with the situation below:

```
on:
  push:
    tags: "v*"                              # Push events to matching v*, i.e. v1.0, v20.15.10
```

I haven't saw any other branch except `master` in this repo and assume the tags "v*" for usual use.

**Comment by emilsoman** [comment]
@Hsins Thank you for your PR! This will need a few changes though. Our goal is to release self-sufficient binaries which also include the right erlang runtime inside it. There's a recent project called bakeware which does something interesting in this regard. Also, what I'm hoping to add is a "latest" release which always reflects what's on the main branch. We have no plans to make `v-` version releases for a while, until some bare necessities are in place in Fika lang.

@eagleusb wanted to discuss his thoughts on this as well, looking forward to the discussion in Discord!

**Comment by Atul9** [comment]
@emilsoman I would like to take this up. I am new to bakeware & how to build binaries. I will check how other opensource project build binaries.

**Comment by Atul9** [comment]
Hi @emilsoman I would like to take this up. I am new to bakeware & how to build binaries. I will check how other opensource project build binaries.

**Comment by emilsoman** [comment]
@Atul9 informed me he is not working on the issue, so this issue is currently unassigned.

**Comment by polvalente** [comment]
I'll tackle this!
