### ISSUE TITLE
Allow Elixir-style string interpolation

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#33]
Allow using `#{}` inside strings which will be expanded and replaced with the string it contains. The expression inside `#{}` should be of string type.

**Comment by gkpacker** [comment]
I'd like to work on this! I have no clue on how to do it, but I will try HAHAHAH

**Comment by gkpacker** [comment]
Is this a valid expression for the erlang interpreter?

```erlang
           {
              :string,
              1,
              [
                {:string, {1, 0, 10}, [72, 101, 108, 108, 111]},
                {:string, 1, ' '},
                {:string, {1, 0, 21}, [87, 111, 114, 108, 100]}
              ]
            }
```

I'll be opening the PR for discussions soon.

**Comment by emilsoman** [comment]
Thanks for looking into this @gkpacker . I don't think that's valid erlang abstract format. The doc is here https://erlang.org/doc/apps/erts/absform.html .
