### ISSUE TITLE
Better data structures for types

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#39]
Right now, types are represented as strings in our AST. For example, the type of [1, 2, 3] is the string "List(Int)". Right now this is fine because type checking is as simple as a string comparison with the expected type, but soon this will be insufficient because we'll have union types. It's a good idea to move to better data structures for holding types before we merge in union types.

Here's the list of all the types we currently have and the proposed data structure to hold them in the AST. So instead of just strings, we'll now have atoms, strings and structs representing types.

```
Booleans - atom :Bool
Atoms (:foo)- string ":<atom>"
Integers - atom :Int
Strings - atom :String
Lists (List(<type>)) - %List{type: <type>}
Records ({foo: <type>, ...}) - %Record{fields: [{<key_atom>, <value_type>}, ...]}
Tuples {<type>, ...} - %Tuple{elements: [<type>, ...]}
Function references - %FunctionRef{arg_types: [<type>, ...], return_type: <type>}
Nothing - atom :Nothing
```

**Comment by polvalente** [comment]
I'll take this on!

**Comment by emilsoman** [comment]
I just noticed all the `<>` were missing because i didn't use the right formatting 🤦  . Fixed it.
