### ISSUE TITLE
Cannot parse functions whose names begin with a keyword

### ISSUE THREAD

**Issue by fabionebbia** [fika-lang/fika#49]
The following examples cause parser error
- `fn fnwathever do`
- `fn dowhatever do`
- `fn ifwhatever do`
- `fn endwhatever do`
- `fn elsewhatever do`

Think problem lies in `Fika.Parser.Common`:
```Elixir
  keyword =
    choice([
      string("fn"),
      string("do"),
      string("end"),
      string("if"),
      string("else")
    ])

  ...

  identifier =
    lookahead_not(keyword)        <--- HERE
    |> concat(identifier_str)
    |> label("identifier")
    |> Helper.to_ast(:identifier)
```

Opening this issue 'cause I couldn't come up with ways to fix it that didn't involve some levels of space handling refactoring.

**Comment by emilsoman** [comment]
Fixed by 28a413cfd! Instead of using lookaheads, we now use post_traverse.
