### ISSUE TITLE
Run tests on CI

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#5]
The goal is to make sure tests pass when code is pushed or when PRs are opened and merged. Make sure to run mix compile with `mix compile --warnings-as-errors` to make sure there are no compilation warnings.

**Comment by Atul9** [comment]
Hi @emilsoman I would like to take this up. I will open PR once hacktoberfest starts.

**Comment by emilsoman** [comment]
@Atul9 issue is yours!
