### ISSUE TITLE
creating fika executable is failing

### ISSUE THREAD

**Issue by anandology** [fika-lang/fika#79]
creating fika executable failing with the following error.

```
$ mix escript.build
** (File.Error) could not write to file "fika": illegal operation on a directory
    (elixir 1.11.3) lib/file.ex:1053: File.write!/3
    (mix 1.11.3) lib/mix/tasks/escript.build.ex:193: Mix.Tasks.Escript.Build.escriptize/2
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

I think this is happening because it is creating a file named `fika`, but there is a directory in the working dir with the same name.

Not sure if `fika/io.fi` is used anywhere.

**Comment by michallepicki** [comment]
I was able to get an executable by running `mix release`. Looks like the readme needs to be updated.

**Comment by emilsoman** [comment]
@michallepicki good catch! I've updated the README.

**Comment by emilsoman** [comment]
@anandology `fika/io.fi` is used to define the functions `gets` and `puts` in Fika-land which use the external functions in BEAM defined by Elixir in the module `Elixir.IO`. These functions are used in example.fi to demonstrate interop with BEAM. Also, it's there as an example to show a quick way to build out our stdlib.
