### ISSUE TITLE
Add if-else expression

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#8]
#### Syntax:
```
if <exp> do
  exps
else
  exps
end
```
if is always followed by an else. This can be parsed into the AST node `{{:if, line}, condition_exp, true_exps, false_exps}`

#### Type checking:
The true_exps and false_exps can return two different things which make the return type a union type (example: `{:ok, Int} | {:error, String}`), but we don't have union types now, so for now we'll just make sure they both return the same type. In short, the type checks needed for now:

1. The condition_exp should be a boolean.
2. The return types of true_exps and false_exps should be the same.

Once these checks pass, the type of the if-else expression is inferred as the type of the true_exps or false_exps blocks.

#### Erl translate
In Erl Abs form, this can be represented as a `case` node.

**Comment by sreecodeslayer** [comment]
am picking this one 👍

**Comment by emilsoman** [comment]
@sreecodeslayer it's yours!
