### ISSUE TITLE
Add comparison operators

### ISSUE THREAD

**Issue by emilsoman** [fika-lang/fika#9]
Fika needs <,>,<=,>=,== and !=.

**Comment by meerasndr** [comment]
@emilsoman Can I take this up?

**Comment by emilsoman** [comment]
@meerasndr it's yours!

**Comment by emilsoman** [comment]
Note - we'll respect the same operator precedence as of Elixir ([link here](https://hexdocs.pm/elixir/master/operators.html#operator-precedence-and-associativity)).

**Comment by emilsoman** [comment]
@meerasndr I've added some [documentation](https://github.com/fika-lang/fika/blob/master/docs/hacking_syntax.md) that should make hacking on Fika's syntax easier. If you find something that I can document better, please let me know.

**Comment by emilsoman** [comment]
@meerasndr I'm freeing up this issue. Feel free to pick up an unassigned issue later whenever you get time.

**Comment by sreecodeslayer** [comment]
shall I take this one?

**Comment by fabionebbia** [comment]
I'd like to take this one

**Comment by emilsoman** [comment]
Done in #42
